stages:
  - install

install_everything:
  variables:
    STOCKFISH_ENGINE_PATH: "/usr/bin/stockfish-17-64"
  stage: install
  script:
    - ./install.sh
    - echo "Installation complete"
    - ./test/test_flask_server.sh
    - echo "All tests passed"